# -*- mode: python ; coding: utf-8 -*-
import os
from PyInstaller.utils.hooks import collect_all, collect_data_files, collect_submodules

block_cipher = None
base_dir = '/Users/alex/Documents/nodex/nodex-panel'

# Collect everything needed for Google API client (discovery cache JSON files
# and dynamic submodules) and Firebase Admin SDK so init_gdrive() and
# init_fcm() actually work inside the PyInstaller bundle.
googleapi_datas, googleapi_binaries, googleapi_imports = collect_all('googleapiclient')
google_auth_datas, google_auth_binaries, google_auth_imports = collect_all('google.auth')
google_oauth2_datas, google_oauth2_binaries, google_oauth2_imports = collect_all('google.oauth2')
google_oauthlib_datas, google_oauthlib_binaries, google_oauthlib_imports = collect_all('google_auth_oauthlib')
firebase_datas, firebase_binaries, firebase_imports = collect_all('firebase_admin')
google_api_core_datas, google_api_core_binaries, google_api_core_imports = collect_all('google.api_core')

a = Analysis(
    [os.path.join(base_dir, 'launcher_universal.py')],
    pathex=[base_dir],
    binaries=googleapi_binaries + google_auth_binaries + google_oauth2_binaries + google_oauthlib_binaries + firebase_binaries + google_api_core_binaries,
    datas=[
        (os.path.join(base_dir, 'templates'), 'templates'),
        (os.path.join(base_dir, 'static'), 'static'),
        (os.path.join(base_dir, 'routes'), 'routes'),
        (os.path.join(base_dir, 'services'), 'services'),
        (os.path.join(base_dir, 'app.py'), '.'),
        (os.path.join(base_dir, 'config.py'), '.'),
        (os.path.join(base_dir, 'models.py'), '.'),
    ] + googleapi_datas + google_auth_datas + google_oauth2_datas + google_oauthlib_datas + firebase_datas + google_api_core_datas,
    hiddenimports=googleapi_imports + google_auth_imports + google_oauth2_imports + google_oauthlib_imports + firebase_imports + google_api_core_imports + [
        'flask',
        'flask_sqlalchemy',
        'sqlalchemy',
        'sqlalchemy.sql.default_comparator',
        'werkzeug',
        'werkzeug.security',
        'jinja2',
        'markupsafe',
        'webview',
        'webview.platforms.cocoa',
        'objc',
        'Foundation',
        'AppKit',
        'WebKit',
        'Quartz',
        'UniformTypeIdentifiers',
        'Security',
        'PyObjCTools',
        'routes',
        'routes.auth',
        'routes.dashboard',
        'routes.payments',
        'routes.projects',
        'routes.tools',
        'routes.tasks',
        'routes.ideas',
        'routes.info',
        'routes.activity',
        'routes.users',
        'routes.settings',
        'routes.credentials',
        'routes.incomes',
        'routes.cowork',
        'routes.api',
        'routes.notifications',
        'routes.clients',
        'routes.invoices',
        'routes.balance',
        'routes.timetracking',
        'routes.calendar',
        'routes.documents',
        'routes.reports',
        'routes.automations',
        'routes.ai_assistant',
        'routes.resources',
        'routes.captacion',
        'routes.objetivos',
        'services',
        'services.activity',
        'services.crypto',
        'services.notifications',
        'services.sync',
        'services.sse',
        'services.presence',
        'services.push',
        'services.gdrive',
        'services.gcal',
        'services.updater',
        'services.native_notify',
        'firebase_admin',
        'firebase_admin.messaging',
        'firebase_admin.credentials',
        'google',
        'google.auth',
        'google.oauth2',
        'google.oauth2.credentials',
        'google.oauth2.service_account',
        'google_auth_oauthlib',
        'google_auth_oauthlib.flow',
        'googleapiclient',
        'googleapiclient.discovery',
        'googleapiclient.http',
        'googleapiclient.errors',
        'googleapiclient.discovery_cache',
        'googleapiclient.discovery_cache.file_cache',
        'httplib2',
        'uritemplate',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.backends',
        'config',
        'models',
        'app',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NodexAI Panel',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NodexAI Panel',
)

app = BUNDLE(
    coll,
    name='NodexAI Panel.app',
    icon='/Users/alex/Documents/nodex/nodex-panel/icon.icns',
    bundle_identifier='es.nodexai.panel',
    info_plist={
        'CFBundleName': 'NodexAI Panel',
        'CFBundleDisplayName': 'NodexAI Panel',
        'CFBundleVersion': '4.5.10',
        'CFBundleShortVersionString': '4.5.10',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '10.15.0',
        'NSCameraUsageDescription': 'NodexAI Panel necesita acceso a la camara para videollamadas.',
        'NSMicrophoneUsageDescription': 'NodexAI Panel necesita acceso al microfono para videollamadas.',
    },
)
