# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None
base_dir = '/Users/alex/Documents/nodex/nodex-panel'

a = Analysis(
    [os.path.join(base_dir, 'launcher_universal.py')],
    pathex=[base_dir],
    binaries=[],
    datas=[
        (os.path.join(base_dir, 'templates'), 'templates'),
        (os.path.join(base_dir, 'static'), 'static'),
        (os.path.join(base_dir, 'routes'), 'routes'),
        (os.path.join(base_dir, 'services'), 'services'),
        (os.path.join(base_dir, 'app.py'), '.'),
        (os.path.join(base_dir, 'config.py'), '.'),
        (os.path.join(base_dir, 'models.py'), '.'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'sqlalchemy',
        'sqlalchemy.sql.default_comparator',
        'werkzeug',
        'werkzeug.security',
        'jinja2',
        'markupsafe',
        'webview',
        'webview.platforms.cocoa',
        'objc',
        'Foundation',
        'AppKit',
        'WebKit',
        'Quartz',
        'UniformTypeIdentifiers',
        'Security',
        'PyObjCTools',
        'routes',
        'routes.auth',
        'routes.dashboard',
        'routes.payments',
        'routes.projects',
        'routes.tools',
        'routes.tasks',
        'routes.ideas',
        'routes.info',
        'routes.activity',
        'routes.users',
        'routes.settings',
        'routes.credentials',
        'routes.incomes',
        'routes.cowork',
        'routes.api',
        'routes.notifications',
        'routes.clients',
        'routes.invoices',
        'routes.balance',
        'routes.timetracking',
        'routes.calendar',
        'routes.documents',
        'routes.reports',
        'routes.automations',
        'routes.ai_assistant',
        'routes.resources',
        'routes.captacion',
        'services',
        'services.activity',
        'services.crypto',
        'services.notifications',
        'services.sync',
        'services.sse',
        'services.presence',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.backends',
        'config',
        'models',
        'app',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NodexAI Panel',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NodexAI Panel',
)

app = BUNDLE(
    coll,
    name='NodexAI Panel.app',
    icon='/Users/alex/Documents/nodex/nodex-panel/icon.icns',
    bundle_identifier='es.nodexai.panel',
    info_plist={
        'CFBundleName': 'NodexAI Panel',
        'CFBundleDisplayName': 'NodexAI Panel',
        'CFBundleVersion': '4.3.0',
        'CFBundleShortVersionString': '4.3.0',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '10.15.0',
        'NSCameraUsageDescription': 'NodexAI Panel necesita acceso a la camara para videollamadas.',
        'NSMicrophoneUsageDescription': 'NodexAI Panel necesita acceso al microfono para videollamadas.',
    },
)
